name: Build .Net App

description: 'Action for building a .NET web app'

runs:
  using: 'composite'
  steps:    
  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 8.0.203
      
  - name: Restore dependencies
    shell: bash
    run: dotnet restore

  - name: Build app
    shell: bash
    run: dotnet build --no-restore
