name: Build .Net App

description: 'Action for building a .NET web app'

runs:
  steps:  
  - name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: 8.0.102
    shell: bash
      
  - name: Restore dependencies
    run: dotnet restore
    shell: bash

  - name: Build app
    run: dotnet build --no-restore
    shell: bash
