name: Build .Net App

description: 'Action for building a .NET web app'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  
  - name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: 8.0.102
      
  - name: Restore dependencies
    run: dotnet restore
    
  - name: Build app
    run: dotnet build --no-restore