// <auto-generated />
using System;
using ConsiliumTempus.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsiliumTempus.Infrastructure.Migrations
{
    [DbContext(typeof(ConsiliumTempusDbContext))]
    partial class ConsiliumTempusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Membership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkspaceRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("WorkspaceRoleId");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ReadWorkspace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UpdateWorkspace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeleteWorkspace"
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("WorkspaceRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role can only read data",
                            Name = "View"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role can do most of the actions with some limitations",
                            Name = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This role can do everything",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Relations.WorkspaceRoleHasPermission", b =>
                {
                    b.Property<int>("WorkspaceRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("WorkspaceRoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("WorkspaceRoleHasPermission", (string)null);

                    b.HasData(
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 3
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.ProjectAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Workspace", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Membership", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", "WorkspaceRole")
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");

                    b.Navigation("WorkspaceRole");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Relations.WorkspaceRoleHasPermission", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.ProjectAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ConsiliumTempus.Domain.Project.Entities.ProjectSprint", "Sprints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("ProjectSprint");

                            b1.WithOwner("Project")
                                .HasForeignKey("ProjectId");

                            b1.OwnsMany("ConsiliumTempus.Domain.Project.Entities.ProjectSection", "Sections", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<Guid>("SprintId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SprintId");

                                    b2.ToTable("ProjectSection");

                                    b2.WithOwner("Sprint")
                                        .HasForeignKey("SprintId");

                                    b2.OwnsMany("ConsiliumTempus.Domain.Project.Entities.ProjectTask", "Tasks", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid?>("AsigneeId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("CreatedById")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<DateTime>("CreatedDateTime")
                                                .HasColumnType("datetime2");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasMaxLength(1000)
                                                .HasColumnType("nvarchar(1000)");

                                            b3.Property<DateOnly?>("DueDate")
                                                .HasColumnType("date");

                                            b3.Property<TimeSpan?>("EstimatedDuration")
                                                .HasColumnType("time");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("nvarchar(100)");

                                            b3.Property<Guid?>("ReviewerId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("SectionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<DateTime>("UpdatedDateTime")
                                                .HasColumnType("datetime2");

                                            b3.HasKey("Id");

                                            b3.HasIndex("AsigneeId");

                                            b3.HasIndex("CreatedById");

                                            b3.HasIndex("ReviewerId");

                                            b3.HasIndex("SectionId");

                                            b3.ToTable("ProjectTask");

                                            b3.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Asignee")
                                                .WithMany()
                                                .HasForeignKey("AsigneeId")
                                                .OnDelete(DeleteBehavior.Cascade);

                                            b3.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "CreatedBy")
                                                .WithMany()
                                                .HasForeignKey("CreatedById")
                                                .OnDelete(DeleteBehavior.Cascade)
                                                .IsRequired();

                                            b3.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Reviewer")
                                                .WithMany()
                                                .HasForeignKey("ReviewerId")
                                                .OnDelete(DeleteBehavior.Cascade);

                                            b3.WithOwner("Section")
                                                .HasForeignKey("SectionId");

                                            b3.OwnsMany("ConsiliumTempus.Domain.Project.Entities.ProjectTaskComment", "Comments", b4 =>
                                                {
                                                    b4.Property<Guid>("Id")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<Guid>("CreatedById")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<DateTime>("CreatedDateTime")
                                                        .HasColumnType("datetime2");

                                                    b4.Property<DateOnly?>("Date")
                                                        .HasColumnType("date");

                                                    b4.Property<string>("Message")
                                                        .IsRequired()
                                                        .HasMaxLength(256)
                                                        .HasColumnType("nvarchar(256)");

                                                    b4.Property<Guid>("TaskId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<TimeSpan?>("TimeSpent")
                                                        .HasColumnType("time");

                                                    b4.Property<DateTime>("UpdatedDateTime")
                                                        .HasColumnType("datetime2");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("CreatedById");

                                                    b4.HasIndex("TaskId");

                                                    b4.ToTable("ProjectTaskComment");

                                                    b4.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "CreatedBy")
                                                        .WithMany()
                                                        .HasForeignKey("CreatedById")
                                                        .OnDelete(DeleteBehavior.Cascade)
                                                        .IsRequired();

                                                    b4.WithOwner("Task")
                                                        .HasForeignKey("TaskId");

                                                    b4.Navigation("CreatedBy");

                                                    b4.Navigation("Task");
                                                });

                                            b3.Navigation("Asignee");

                                            b3.Navigation("Comments");

                                            b3.Navigation("CreatedBy");

                                            b3.Navigation("Reviewer");

                                            b3.Navigation("Section");
                                        });

                                    b2.Navigation("Sprint");

                                    b2.Navigation("Tasks");
                                });

                            b1.Navigation("Project");

                            b1.Navigation("Sections");
                        });

                    b.Navigation("Sprints");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.Credentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.HasKey("UserAggregateId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("Last")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserAggregateId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
