// <auto-generated />
using System;
using ConsiliumTempus.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsiliumTempus.Infrastructure.Migrations
{
    [DbContext(typeof(ConsiliumTempusDbContext))]
    partial class ConsiliumTempusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsiliumTempus.Domain.Announcement.AnnouncementAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Audit", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Membership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("_workspaceRoleId")
                        .HasColumnType("int")
                        .HasColumnName("WorkspaceRoleId");

                    b.HasKey("UserId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("_workspaceRoleId");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ReadWorkspace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UpdateWorkspace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeleteWorkspace"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CreateProject"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ReadProject"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ReadCollectionProject"
                        },
                        new
                        {
                            Id = 7,
                            Name = "UpdateProject"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DeleteProject"
                        },
                        new
                        {
                            Id = 9,
                            Name = "AddStatusToProject"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ReadStatusesFromProject"
                        },
                        new
                        {
                            Id = 11,
                            Name = "UpdateStatusFromProject"
                        },
                        new
                        {
                            Id = 12,
                            Name = "RemoveStatusFromProject"
                        },
                        new
                        {
                            Id = 13,
                            Name = "CreateProjectSprint"
                        },
                        new
                        {
                            Id = 14,
                            Name = "ReadProjectSprint"
                        },
                        new
                        {
                            Id = 15,
                            Name = "ReadCollectionProjectSprint"
                        },
                        new
                        {
                            Id = 16,
                            Name = "UpdateProjectSprint"
                        },
                        new
                        {
                            Id = 17,
                            Name = "DeleteProjectSprint"
                        },
                        new
                        {
                            Id = 18,
                            Name = "AddStageToProjectSprint"
                        },
                        new
                        {
                            Id = 19,
                            Name = "UpdateStageFromProjectSprint"
                        },
                        new
                        {
                            Id = 20,
                            Name = "RemoveStageFromProjectSprint"
                        },
                        new
                        {
                            Id = 21,
                            Name = "CreateProjectTask"
                        },
                        new
                        {
                            Id = 22,
                            Name = "ReadProjectTask"
                        },
                        new
                        {
                            Id = 23,
                            Name = "ReadCollectionProjectTask"
                        },
                        new
                        {
                            Id = 24,
                            Name = "UpdateProjectTask"
                        },
                        new
                        {
                            Id = 25,
                            Name = "DeleteProjectTask"
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("WorkspaceRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role can only read data",
                            Name = "View"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role can do most of the actions with some limitations",
                            Name = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This role can do everything",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Relations.WorkspaceRoleHasPermission", b =>
                {
                    b.Property<int>("WorkspaceRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("WorkspaceRoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("WorkspaceRoleHasPermission", (string)null);

                    b.HasData(
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            WorkspaceRoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 24
                        },
                        new
                        {
                            WorkspaceRoleId = 2,
                            PermissionId = 25
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 21
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 22
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 23
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 24
                        },
                        new
                        {
                            WorkspaceRoleId = 3,
                            PermissionId = 25
                        });
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.Entities.ProjectStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectStatus", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.ProjectAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.Entities.ProjectStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("SprintId");

                    b.ToTable("ProjectStage", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.ProjectSprintAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSprint", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectTask.ProjectTaskAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EstimatedDuration")
                        .HasColumnType("time");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StageId");

                    b.ToTable("ProjectTask", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Workspace", (string)null);
                });

            modelBuilder.Entity("ProjectAggregateUserAggregate", b =>
                {
                    b.Property<Guid>("FavoritesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectId");

                    b.HasKey("FavoritesId", "ProjectAggregateId");

                    b.HasIndex("ProjectAggregateId");

                    b.ToTable("UserHasFavoriteProject", (string)null);
                });

            modelBuilder.Entity("UserAggregateWorkspaceAggregate", b =>
                {
                    b.Property<Guid>("FavoritesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceAggregateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("FavoritesId", "WorkspaceAggregateId");

                    b.HasIndex("WorkspaceAggregateId");

                    b.ToTable("UserHasFavoriteWorkspace", (string)null);
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Announcement.AnnouncementAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Project.ProjectAggregate", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId");

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("AnnouncementAggregateId");

                            b1.ToTable("Announcement");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("AnnouncementAggregateId");

                            b1.ToTable("Announcement");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementAggregateId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ConsiliumTempus.Domain.Authentication.RefreshTokenHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("RefreshTokenId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RefreshTokenId");

                            b1.ToTable("RefreshTokenHistory", (string)null);

                            b1.WithOwner("RefreshToken")
                                .HasForeignKey("RefreshTokenId");

                            b1.OwnsOne("ConsiliumTempus.Domain.Authentication.ValueObjects.JwtId", "JwtId", b2 =>
                                {
                                    b2.Property<Guid>("RefreshTokenHistoryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("JwtId");

                                    b2.HasKey("RefreshTokenHistoryId");

                                    b2.ToTable("RefreshTokenHistory");

                                    b2.WithOwner()
                                        .HasForeignKey("RefreshTokenHistoryId");
                                });

                            b1.Navigation("JwtId")
                                .IsRequired();

                            b1.Navigation("RefreshToken");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Authentication.ValueObjects.IsInvalidated", "IsInvalidated", b1 =>
                        {
                            b1.Property<Guid>("RefreshTokenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("IsInvalidated");

                            b1.HasKey("RefreshTokenId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("RefreshTokenId");
                        });

                    b.Navigation("History");

                    b.Navigation("IsInvalidated")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Audit", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Entities.Membership", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", null)
                        .WithMany()
                        .HasForeignKey("_workspaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Common.Relations.WorkspaceRoleHasPermission", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.WorkspaceRole", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.Entities.ProjectStatus", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Project.ProjectAggregate", "Project")
                        .WithMany("Statuses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("ProjectStatusId");

                            b1.ToTable("ProjectStatus");

                            b1.WithOwner()
                                .HasForeignKey("ProjectStatusId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("ProjectStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Title");

                            b1.HasKey("ProjectStatusId");

                            b1.ToTable("ProjectStatus");

                            b1.WithOwner()
                                .HasForeignKey("ProjectStatusId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.ProjectAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.IsPrivate", "IsPrivate", b1 =>
                        {
                            b1.Property<Guid>("ProjectAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("IsPrivate");

                            b1.HasKey("ProjectAggregateId");

                            b1.ToTable("Project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("ProjectAggregateId");

                            b1.ToTable("Project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProjectAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("ProjectAggregateId");

                            b1.ToTable("Project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectAggregateId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("IsPrivate")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.Entities.ProjectStage", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.ProjectSprint.ProjectSprintAggregate", "Sprint")
                        .WithMany("Stages")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.CustomOrderPosition", "CustomOrderPosition", b1 =>
                        {
                            b1.Property<Guid>("ProjectStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("CustomOrderPosition");

                            b1.HasKey("ProjectStageId");

                            b1.ToTable("ProjectStage");

                            b1.WithOwner()
                                .HasForeignKey("ProjectStageId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProjectStageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.HasKey("ProjectStageId");

                            b1.ToTable("ProjectStage");

                            b1.WithOwner()
                                .HasForeignKey("ProjectStageId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("CustomOrderPosition")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.ProjectSprintAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.Common.Entities.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Project.ProjectAggregate", "Project")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProjectSprintAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.HasKey("ProjectSprintAggregateId");

                            b1.ToTable("ProjectSprint");

                            b1.WithOwner()
                                .HasForeignKey("ProjectSprintAggregateId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectTask.ProjectTaskAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId");

                    b.HasOne("ConsiliumTempus.Domain.ProjectSprint.Entities.ProjectStage", "Stage")
                        .WithMany("Tasks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.CustomOrderPosition", "CustomOrderPosition", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("CustomOrderPosition");

                            b1.HasKey("ProjectTaskAggregateId");

                            b1.ToTable("ProjectTask");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("ProjectTaskAggregateId");

                            b1.ToTable("ProjectTask");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Name");

                            b1.HasKey("ProjectTaskAggregateId");

                            b1.ToTable("ProjectTask");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.ProjectTask.ValueObjects.IsCompleted", "IsCompleted", b1 =>
                        {
                            b1.Property<Guid>("ProjectTaskAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("IsCompleted");

                            b1.HasKey("ProjectTaskAggregateId");

                            b1.ToTable("ProjectTask");

                            b1.WithOwner()
                                .HasForeignKey("ProjectTaskAggregateId");
                        });

                    b.OwnsMany("ConsiliumTempus.Domain.ProjectTask.Entities.ProjectTaskComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CreatedById")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("TaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan?>("TimeSpent")
                                .HasColumnType("time");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("CreatedById");

                            b1.HasIndex("TaskId");

                            b1.ToTable("ProjectTaskComment", (string)null);

                            b1.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner("Task")
                                .HasForeignKey("TaskId");

                            b1.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Message", "Message", b2 =>
                                {
                                    b2.Property<Guid>("ProjectTaskCommentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("Message");

                                    b2.HasKey("ProjectTaskCommentId");

                                    b2.ToTable("ProjectTaskComment");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectTaskCommentId");
                                });

                            b1.Navigation("CreatedBy");

                            b1.Navigation("Message")
                                .IsRequired();

                            b1.Navigation("Task");
                        });

                    b.Navigation("Assignee");

                    b.Navigation("Comments");

                    b.Navigation("CreatedBy");

                    b.Navigation("CustomOrderPosition")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("IsCompleted")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.Credentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Password");

                            b1.HasKey("UserAggregateId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.HasKey("UserAggregateId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.LastName", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserAggregateId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.User.ValueObjects.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Role");

                            b1.HasKey("UserAggregateId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserAggregateId");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("ConsiliumTempus.Domain.Workspace.ValueObjects.IsPersonal", "IsPersonal", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("IsPersonal");

                            b1.HasKey("WorkspaceAggregateId");

                            b1.ToTable("Workspace");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("WorkspaceAggregateId");

                            b1.ToTable("Workspace");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceAggregateId");
                        });

                    b.OwnsOne("ConsiliumTempus.Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("WorkspaceAggregateId");

                            b1.ToTable("Workspace");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceAggregateId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("IsPersonal")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectAggregateUserAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Project.ProjectAggregate", null)
                        .WithMany()
                        .HasForeignKey("ProjectAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserAggregateWorkspaceAggregate", b =>
                {
                    b.HasOne("ConsiliumTempus.Domain.User.UserAggregate", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Project.ProjectAggregate", b =>
                {
                    b.Navigation("Sprints");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.Entities.ProjectStage", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.ProjectSprint.ProjectSprintAggregate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.User.UserAggregate", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ConsiliumTempus.Domain.Workspace.WorkspaceAggregate", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
