name: Build 🔨

on:
  workflow_call: 
    inputs:
      test-env:
        type: string
        required: true
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.102
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build app
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --verbosity normal --filter "FullyQualifiedName~${{ test-env }}" --no-build