name: Build 🔨

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Building
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Build
      uses: ./.github/workflows/build-action