name: Testing 🧪

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  
  unit-test:
    uses: ./.github/workflows/build.yaml
    with:
      test-env: UnitTests
  
  integration-test:
    uses: ./.github/workflows/build.yaml
    with:
      test-env: IntegrationTests